# Generated by Django 4.2.6 on 2023-11-03 03:47

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_photo',
            field=models.ImageField(help_text='Разрешается формата файла только jpg, jpeg, png, bmp', max_length=254, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp']), catalog.models.Request.validate_image], verbose_name='Фотография'),
        ),
    ]
