# Generated by Django 4.2.6 on 2023-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_designcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('process', 'Принято в работу'), ('made', 'Выполнено')], default='new', max_length=25, verbose_name='Статус заявки'),
        ),
    ]
