# Generated by Django 4.2.6 on 2023-11-07 15:06

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='design_file',
            field=models.ImageField(blank=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'bmp']), catalog.models.Request.validate_image]),
        ),
    ]
